# -*- coding: utf-8 -*-
"""Image DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lzz_3CyR8swlp_gZy5Sgx_T6Bmao2gvQ
"""

import pandas as pd

!pip install tensorflow
import numpy as pd

from tensorflow.keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

import matplotlib.pyplot as plt

x_train.shape

x_test.shape

single_image = x_train[1]

single_image

single_image.min()

plt.imshow(single_image)

y_train

y_train.shape

y_test

y_test.shape

from tensorflow.keras.utils import to_categorical

y_cat_train=to_categorical(y_train)

y_cat_train[0]

y_cat_train.shape

y_cat_test=to_categorical(y_test)

y_cat_test.shape

x_train=x_test/255
x_test=x_test/255

x_train[0].max()

x_train[0].min()



x_train=x_train/255
x_test=x_test/255



"""After correcting cell `kejO0V6QaWTs`, you can then reshape `x_train` and `x_test`."""

plt.imshow(x_train[0])

x_train=x_train.reshape(10000,28,28,1)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten

model = Sequential()

model.add(Conv2D(filters=32, kernel_size=(4,4), input_shape=(28,28,1), activation='relu'))

model.add(MaxPool2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.summary()

from tensorflow.keras.callbacks import EarlyStopping
early_stop = EarlyStopping(monitor='val_loss', patience=2)

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(x_train, y_cat_train, epochs=10, validation_data=(x_test, y_cat_test), callbacks=[early_stop])

model.metrics_names

model.evaluate(x_test,y_cat_test)

y_test_pred=model.predict(x_test)

#write a program to convert video into frame



losses[['accuracy','val_accuracy']]